BINARY     := seo-report
CMD        := ./cmd/seo-report
DATE       := $(shell date -u +%Y-%m-%d)
BRANCH     := chore/seo-report-$(DATE)

.PHONY: help build generate test clean sources commit pr merge gh-release release

.DEFAULT_GOAL := help

##@ General

help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

build: ## Compile the seo-report binary
	go build -o $(BINARY) $(CMD)

test: ## Run all tests
	go test ./...

clean: ## Remove the compiled binary
	rm -f $(BINARY)

sources: build ## List all configured RSS sources
	./$(BINARY) sources

##@ Reporting

generate: build ## Fetch sources, classify, score, and write docs/
	./$(BINARY) generate

dry-run: build ## Preview today's report without writing files
	./$(BINARY) generate --dry-run

##@ Release

commit: ## Create a branch and commit today's generated report
	@if [ -z "$$(git status --porcelain docs/)" ]; then \
		echo "Nothing to commit in docs/ — run 'make generate' first."; \
		exit 1; \
	fi
	git checkout -b $(BRANCH)
	git add docs/
	git commit -m "chore: daily SEO report for $(DATE)"

pr: ## Push branch and open a draft PR
	@CURRENT=$$(git rev-parse --abbrev-ref HEAD); \
	if [ "$$CURRENT" = "main" ] || [ "$$CURRENT" = "master" ]; then \
		echo "Already on default branch — run 'make commit' first."; \
		exit 1; \
	fi
	git push -u origin $$(git rev-parse --abbrev-ref HEAD)
	gh pr create --draft \
		--title "chore: daily SEO report for $(DATE)" \
		--body "Automated daily AEO/SEO digest for $(DATE). Generated by \`make release\`."

merge: ## Mark open PR as ready and merge it
	@PR=$$(gh pr view --json number --jq '.number' 2>/dev/null); \
	if [ -z "$$PR" ]; then \
		echo "No open PR found for this branch."; \
		exit 1; \
	fi; \
	gh pr ready $$PR && gh pr merge $$PR --squash --delete-branch
	git checkout main
	git pull --ff-only origin main

gh-release: ## Create a versioned GitHub release tagged v<DATE>
	gh release create "v$(DATE)" \
		--title "SEO Report $(DATE)" \
		--notes "Daily AEO/SEO digest for $(DATE). View the report at https://lankeami.github.io/seo-report/$(DATE).html"

release: generate commit pr merge gh-release ## Full pipeline: fetch → report → commit → PR → merge → GitHub release
